name: Aurora
description: Illuminate the night with breathtaking ambient particle effects
version: ${project.version}
author: Optic_Fusion1
main: com.zenya.aurora.Aurora
api-version: 1.18
softdepend: [WorldGuard, LightAPI]

libraries:
  - org.bstats:bstats-bukkit:${bstats.bukkit}
  - co.aikar:acf-paper:${acf.version}
  - org.xerial:sqlite-jdbc:${sqlite.jdbc.version}

permissions:
  aurora.*:
    children:
      aurora.command.help: true
      aurora.command.toggle: true
      aurora.command.reload: true
      aurora.command.status: true
      aurora.command.fixlighting: true
      aurora.view: true
  aurora.command.*:
    children:
      aurora.command.help: true
      aurora.command.toggle: true
      aurora.command.reload: true
      aurora.command.status: true
      aurora.command.fixlighting: true
  aurora.command.help:
    default: true
  aurora.command.toggle:
    default: true
  aurora.command.reload:
    default: op
  aurora.command.status:
    default: op
  aurora.command.fixlighting:
    default: op
  aurora.view:
    default: true